name:                hw1
version:             0.1.0.0
github:              "https://github.com/andresokol/hw1"
license:             MIT
author:              "Andrey Sokolov"
maintainer:          "sokolov-as-i@yandex.ru"
copyright:           "2020 Andrey Sokolov <sokolov-as-i@yandex.ru>"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andresokol/hw1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hw1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1

tests:
  hw1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
